import type {
  EvidenceReference,
  PartyDefinition,
  PartyId,
} from '../core/contracts'

export const PARTY_CONTENT_AS_OF = '2026-09-11'
export const LINDENHAFEN_COUNCIL_SEATS = 60

export const PARTY_EVIDENCE: EvidenceReference[] = [
  {
    id: 'federal-election-result-2025',
    publisher: 'Die Bundeswahlleiterin',
    title: 'Bundestagswahl 2025 – endgültiges Ergebnis Deutschland',
    url: 'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/bund-99.html',
    publishedAt: '2025-03-14',
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'baseline',
    applicability: 'Bundesweites Wahlergebnis als politischer Zeitkontext; keine Übertragung auf den fiktiven Stadtrat.',
  },
  {
    id: 'bundestag-fraktionen-2026',
    publisher: 'Deutscher Bundestag',
    title: 'Fraktionen des 21. Deutschen Bundestages',
    url: 'https://www.bundestag.de/parlament/fraktionen',
    publishedAt: '2026-08-21',
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'baseline',
    applicability: 'Fraktionslandschaft zum Stichtag; Lindenhafen verwendet eigene fiktive Ratsmandate.',
  },
  {
    id: 'cdu-program-2025',
    publisher: 'CDU Deutschlands',
    title: 'Wahlprogramm von CDU und CSU zur Bundestagswahl 2025',
    url: 'https://www.cdu.de/wahlprogramm-von-cdu-und-csu/',
    publishedAt: null,
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'position',
    applicability: 'Bundespolitische Positionen werden nur als Inspiration für kommunale, fiktive Politikpräferenzen verwendet.',
    notes: 'Die offizielle Programmseite weist im ausgelesenen Dokument kein belastbares Veröffentlichungsdatum aus.',
  },
  {
    id: 'afd-program-2025',
    publisher: 'Alternative für Deutschland',
    title: 'Bundestagswahlprogramm 2025',
    url: 'https://www.afd.de/wahlprogramm25/',
    publishedAt: null,
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'position',
    applicability: 'Bundespolitische Positionen werden nur als Inspiration für kommunale, fiktive Politikpräferenzen verwendet.',
    notes: 'Programmversion 2025; die offizielle Übersichtsseite weist kein belastbares Veröffentlichungsdatum aus.',
  },
  {
    id: 'spd-program-2025',
    publisher: 'SPD',
    title: 'Mehr für Dich. Besser für Deutschland. – Regierungsprogramm 2025',
    url: 'https://www.spd.de/fileadmin/Dokumente/Beschluesse/Programm/2025_SPD_Regierungsprogramm.pdf',
    publishedAt: null,
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'position',
    applicability: 'Bundespolitische Positionen werden nur als Inspiration für kommunale, fiktive Politikpräferenzen verwendet.',
    notes: 'Offizielle Programmfassung zur Bundestagswahl 2025.',
  },
  {
    id: 'greens-program-2025',
    publisher: 'Bündnis 90/Die Grünen',
    title: 'Zusammen wachsen – Regierungsprogramm 2025',
    url: 'https://www.gruene.de/artikel/zusammen-wachsen',
    publishedAt: null,
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'position',
    applicability: 'Bundespolitische Positionen werden nur als Inspiration für kommunale, fiktive Politikpräferenzen verwendet.',
    notes: 'Offizielle Programmseite zur Bundestagswahl 2025.',
  },
  {
    id: 'left-program-2025',
    publisher: 'Die Linke',
    title: 'Alle wollen regieren. Wir wollen verändern. – Wahlprogramm 2025',
    url: 'https://www.die-linke.de/bundestagswahl-2025/wahlprogramm/',
    publishedAt: null,
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'position',
    applicability: 'Bundespolitische Positionen werden nur als Inspiration für kommunale, fiktive Politikpräferenzen verwendet.',
    notes: 'Offizielle Programmseite zur Bundestagswahl 2025.',
  },
  {
    id: 'fdp-program-2025',
    publisher: 'FDP',
    title: 'Das Wahlprogramm der Freien Demokraten zur Bundestagswahl 2025',
    url: 'https://www.fdp.de/das-wahlprogramm-der-freien-demokraten-zur-bundestagswahl-2025',
    publishedAt: '2024-12-18',
    accessedAt: PARTY_CONTENT_AS_OF,
    claimType: 'position',
    applicability: 'Bundespolitische Positionen werden nur als Inspiration für kommunale, fiktive Politikpräferenzen verwendet.',
  },
]

export const PARTIES: PartyDefinition[] = [
  {
    schemaVersion: 1,
    id: 'cdu',
    abbreviation: 'CDU',
    name: 'Civile Demokratische Union',
    color: '#24272b',
    textColor: '#f4f0e6',
    emblem: 'C',
    summary: 'Eine konservativ-bürgerliche Kraft mit Fokus auf Verwaltung, Wirtschaft und kommunale Ordnung.',
    strengths: ['Verwaltungsroutine', 'Wirtschaftsnetzwerke'],
    tradeoffs: ['Langsame Kurswechsel', 'Kompromisse kosten Einfluss'],
    focusPriorityIds: ['employment', 'fiscalHealth', 'housing'],
    policyPositions: [
      { policyId: 'cdu-commercial-land', stance: 'support', rationale: 'Gewerbeansiedlung und zügige Planverfahren stehen im Zentrum der wirtschaftspolitischen Programmlinie.', sourceIds: ['cdu-program-2025'] },
      { policyId: 'cdu-order-service', stance: 'support', rationale: 'Sichtbare Ordnungspräsenz entspricht dem programmatischen Schwerpunkt auf innerer Sicherheit.', sourceIds: ['cdu-program-2025'] },
      { policyId: 'cdu-family-land', stance: 'support', rationale: 'Eigentumsbildung für Familien ist eine tragende wohnungspolitische Forderung des Programms.', sourceIds: ['cdu-program-2025'] },
      { policyId: 'cdu-debt-brake', stance: 'support', rationale: 'Haushaltsdisziplin und die Bindung neuer Ausgaben an Gegenfinanzierung sind programmatischer Kern.', sourceIds: ['cdu-program-2025'] },
      { policyId: 'shared-consolidation', stance: 'support', rationale: 'Konsolidierung entspricht der haushaltspolitischen Programmlinie.', sourceIds: ['cdu-program-2025'] },
      { policyId: 'shared-maintenance', stance: 'conditional', rationale: 'Werterhalt wird befürwortet, die dauerhafte Ausgabenbindung bleibt Verhandlungssache.', sourceIds: ['cdu-program-2025'] },
      { policyId: 'shared-block-renewal', stance: 'support', rationale: 'Bestandssanierung vor Neubau, und Eigentum, das gepflegt wird, hält seinen Wert.', sourceIds: ['cdu-program-2025'] },
    ],
    axes: { fiscalRestraint: 0.6, marketVsPublic: 0.5, growthVsPreservation: 0.2, climateAmbition: -0.1, redistribution: -0.3, securityAuthority: 0.6, opennessIntegration: -0.3 },
    redLines: [{ axis: 'securityAuthority', operator: '<', value: -0.6, reason: 'Abbau von Ordnungs- und Sicherheitsstrukturen wird nicht mitgetragen.' }],
    stats: { councilSeats: 18, publicSupport: 30, organization: 78, negotiation: 72 },
    sourceIds: ['cdu-program-2025', 'federal-election-result-2025', 'bundestag-fraktionen-2026'],
    asOf: PARTY_CONTENT_AS_OF,
  },
  {
    schemaVersion: 1,
    id: 'afd',
    abbreviation: 'AfD',
    name: 'Alternative für Demokratie',
    color: '#1d659f',
    textColor: '#f4f0e6',
    emblem: 'A',
    summary: 'Eine nationalkonservative Protestkraft mit starkem Fokus auf Begrenzung, Ordnung und konfrontative Opposition.',
    strengths: ['Hohe Mobilisierung', 'Klares Oppositionsprofil'],
    tradeoffs: ['Begrenzte Mehrheitsoptionen', 'Konfliktreiche Ratsarbeit'],
    focusPriorityIds: ['fiscalHealth', 'employment', 'cohesion'],
    policyPositions: [
      { policyId: 'afd-cctv-network', stance: 'support', rationale: 'Ausbau der Videoüberwachung ist eine ausdrückliche sicherheitspolitische Forderung.', sourceIds: ['afd-program-2025'] },
      { policyId: 'afd-townscape', stance: 'support', rationale: 'Der Schutz gewachsener Ortsbilder gegen Verdichtung entspricht der Programmlinie.', sourceIds: ['afd-program-2025'] },
      { policyId: 'afd-roads-first', stance: 'support', rationale: 'Umschichtung von Klimastellen in Straßenunterhalt folgt der ablehnenden Haltung zu kommunaler Klimapolitik.', sourceIds: ['afd-program-2025'] },
      { policyId: 'afd-referendum', stance: 'support', rationale: 'Direktdemokratische Entscheidung über Großvorhaben ist eine durchgängige Programmforderung.', sourceIds: ['afd-program-2025'] },
      { policyId: 'shared-consolidation', stance: 'support', rationale: 'Ausgabenkürzung bei freiwilligen Leistungen entspricht der haushaltspolitischen Linie.', sourceIds: ['afd-program-2025'] },
      { policyId: 'shared-maintenance', stance: 'support', rationale: 'Werterhalt bestehender Infrastruktur hat im Programm Vorrang vor neuen Vorhaben.', sourceIds: ['afd-program-2025'] },
      { policyId: 'shared-block-renewal', stance: 'conditional', rationale: 'Sanierung ja — aber keine Auflagen, die das Wohnen am Ende teurer machen als der Verfall.', sourceIds: ['afd-program-2025'] },
    ],
    axes: { fiscalRestraint: 0.5, marketVsPublic: 0.3, growthVsPreservation: 0.6, climateAmbition: -0.9, redistribution: -0.2, securityAuthority: 0.9, opennessIntegration: -0.9 },
    redLines: [{ axis: 'opennessIntegration', operator: '>', value: 0.6, reason: 'Ausbau von Zuwanderungs- und Integrationsangeboten wird abgelehnt.' }],
    stats: { councilSeats: 13, publicSupport: 22, organization: 73, negotiation: 34 },
    sourceIds: ['afd-program-2025', 'federal-election-result-2025', 'bundestag-fraktionen-2026'],
    asOf: PARTY_CONTENT_AS_OF,
  },
  {
    schemaVersion: 1,
    id: 'spd',
    abbreviation: 'SPD',
    name: 'Sozialer Progress Deutschland',
    color: '#b52337',
    textColor: '#f4f0e6',
    emblem: 'S',
    summary: 'Eine sozialdemokratische Kraft für bezahlbares Wohnen, öffentliche Dienste und breite Bündnisse.',
    strengths: ['Sozialer Ausgleich', 'Kommunale Daseinsvorsorge'],
    tradeoffs: ['Hohe laufende Kosten', 'Breite Bündnisse brauchen Zeit'],
    focusPriorityIds: ['housing', 'employment', 'cohesion'],
    policyPositions: [
      { policyId: 'housing-accelerator', stance: 'support', rationale: 'Kommunaler Wohnungsbau und schnellere Genehmigungen sind wohnungspolitischer Programmkern.', sourceIds: ['spd-program-2025'] },
      { policyId: 'spd-training-guarantee', stance: 'support', rationale: 'Eine Ausbildungsgarantie steht ausdrücklich im arbeitsmarktpolitischen Teil des Programms.', sourceIds: ['spd-program-2025'] },
      { policyId: 'spd-social-ticket', stance: 'support', rationale: 'Vergünstigte Mobilität für Geringverdienende entspricht der Programmlinie zur Teilhabe.', sourceIds: ['spd-program-2025'] },
      { policyId: 'spd-procurement', stance: 'support', rationale: 'Tariftreue bei öffentlichen Aufträgen ist eine tragende Forderung des Programms.', sourceIds: ['spd-program-2025'] },
      { policyId: 'shared-consolidation', stance: 'oppose', rationale: 'Pauschale Kürzung freiwilliger Leistungen trifft die soziale Infrastruktur, die das Programm sichern will.', sourceIds: ['spd-program-2025'] },
      { policyId: 'shared-maintenance', stance: 'support', rationale: 'Verlässlicher Unterhalt öffentlicher Einrichtungen entspricht der Programmlinie.', sourceIds: ['spd-program-2025'] },
      { policyId: 'shared-block-renewal', stance: 'conditional', rationale: 'Instandsetzung ist geboten, die Verdrängung danach ist es nicht: nur mit Mietbindung im Block.', sourceIds: ['spd-program-2025'] },
    ],
    axes: { fiscalRestraint: -0.4, marketVsPublic: -0.5, growthVsPreservation: -0.4, climateAmbition: 0.3, redistribution: 0.6, securityAuthority: 0.1, opennessIntegration: 0.4 },
    redLines: [{ axis: 'redistribution', operator: '<', value: -0.6, reason: 'Maßnahmen zulasten niedriger Einkommen werden nicht mitgetragen.' }],
    stats: { councilSeats: 13, publicSupport: 22, organization: 76, negotiation: 82 },
    sourceIds: ['spd-program-2025', 'federal-election-result-2025', 'bundestag-fraktionen-2026'],
    asOf: PARTY_CONTENT_AS_OF,
  },
  {
    schemaVersion: 1,
    id: 'gruene',
    abbreviation: 'GRÜNE',
    name: 'Gemeinschaft für Regionale Umwelt, Nachhaltigkeit und Erneuerung',
    color: '#286531',
    textColor: '#f4f0e6',
    emblem: 'G',
    summary: 'Eine ökologisch-progressive Kraft für klimaneutrale Quartiere, öffentlichen Verkehr und Teilhabe.',
    strengths: ['Verkehrswende', 'Klima-Investitionen'],
    tradeoffs: ['Hoher Investitionsbedarf', 'Konflikte um Flächennutzung'],
    focusPriorityIds: ['climate', 'mobility', 'cohesion'],
    policyPositions: [
      { policyId: 'transit-network', stance: 'support', rationale: 'Ausbau des Nahverkehrs und dichtere Takte sind verkehrspolitischer Programmkern.', sourceIds: ['greens-program-2025'] },
      { policyId: 'gruene-cycle-network', stance: 'support', rationale: 'Ein zusammenhängendes, geschütztes Radnetz ist eine ausdrückliche Programmforderung.', sourceIds: ['greens-program-2025'] },
      { policyId: 'gruene-heat-plan', stance: 'support', rationale: 'Kommunale Wärmeplanung und Quartiersnetze stehen im energiepolitischen Teil des Programms.', sourceIds: ['greens-program-2025'] },
      { policyId: 'gruene-unsealing', stance: 'support', rationale: 'Entsiegelung und Regenwasserrückhalt entsprechen der Programmlinie zur Klimaanpassung.', sourceIds: ['greens-program-2025'] },
      { policyId: 'shared-consolidation', stance: 'oppose', rationale: 'Eine Kürzung quer durch die freiwilligen Leistungen trifft Klima- und Teilhabeaufgaben zuerst.', sourceIds: ['greens-program-2025'] },
      { policyId: 'shared-maintenance', stance: 'support', rationale: 'Werterhalt statt Neubau entspricht dem Ressourcenschutzgedanken des Programms.', sourceIds: ['greens-program-2025'] },
      { policyId: 'shared-block-renewal', stance: 'support', rationale: 'Bestand sanieren spart Grauenergie gegenüber Abriss und Neubau — die ressourcenschonende Wahl.', sourceIds: ['greens-program-2025'] },
    ],
    axes: { fiscalRestraint: -0.3, marketVsPublic: -0.3, growthVsPreservation: -0.2, climateAmbition: 0.9, redistribution: 0.4, securityAuthority: -0.5, opennessIntegration: 0.8 },
    redLines: [{ axis: 'climateAmbition', operator: '<', value: -0.5, reason: 'Beschlüsse gegen die kommunalen Klimaziele werden nicht mitgetragen.' }],
    stats: { councilSeats: 8, publicSupport: 13, organization: 67, negotiation: 71 },
    sourceIds: ['greens-program-2025', 'federal-election-result-2025', 'bundestag-fraktionen-2026'],
    asOf: PARTY_CONTENT_AS_OF,
  },
  {
    schemaVersion: 1,
    id: 'linke',
    abbreviation: 'LINKE',
    name: 'Lindenhafener Initiative für Neue Kommunale Entwicklung',
    color: '#98295e',
    textColor: '#f4f0e6',
    emblem: 'L',
    summary: 'Eine demokratisch-sozialistische Stadtallianz mit Schwerpunkt auf Mieten, Umverteilung und öffentlicher Infrastruktur.',
    strengths: ['Mieterschutz', 'Öffentliche Infrastruktur'],
    tradeoffs: ['Hoher Finanzierungsbedarf', 'Schmale Koalitionsbasis'],
    focusPriorityIds: ['housing', 'cohesion', 'mobility'],
    policyPositions: [
      { policyId: 'linke-buy-back', stance: 'support', rationale: 'Rekommunalisierung von Wohnungsbeständen und dauerhafte Bindung sind wohnungspolitischer Programmkern.', sourceIds: ['left-program-2025'] },
      { policyId: 'linke-free-transit', stance: 'support', rationale: 'Der fahrscheinlose Nahverkehr ist eine ausdrückliche Programmforderung.', sourceIds: ['left-program-2025'] },
      { policyId: 'linke-remunicipalise', stance: 'support', rationale: 'Rückführung privatisierter Daseinsvorsorge in kommunale Hand steht durchgängig im Programm.', sourceIds: ['left-program-2025'] },
      { policyId: 'linke-employment-company', stance: 'support', rationale: 'Öffentlich geförderte Beschäftigung ist eine tragende arbeitsmarktpolitische Forderung.', sourceIds: ['left-program-2025'] },
      { policyId: 'shared-consolidation', stance: 'oppose', rationale: 'Kürzungen bei freiwilligen Leistungen widersprechen dem sozialpolitischen Programmkern.', sourceIds: ['left-program-2025'] },
      { policyId: 'shared-maintenance', stance: 'support', rationale: 'Instandhaltung öffentlicher Daseinsvorsorge ist programmatisch geboten.', sourceIds: ['left-program-2025'] },
      { policyId: 'shared-block-renewal', stance: 'oppose', rationale: 'Sanierung ohne Mietendeckel ist Verdrängung mit Gerüst davor; so nicht.', sourceIds: ['left-program-2025'] },
    ],
    axes: { fiscalRestraint: -0.7, marketVsPublic: -0.9, growthVsPreservation: -0.3, climateAmbition: 0.6, redistribution: 0.9, securityAuthority: -0.7, opennessIntegration: 0.9 },
    redLines: [{ axis: 'marketVsPublic', operator: '>', value: 0.6, reason: 'Privatisierung kommunaler Daseinsvorsorge wird abgelehnt.' }],
    stats: { councilSeats: 5, publicSupport: 8, organization: 61, negotiation: 52 },
    sourceIds: ['left-program-2025', 'federal-election-result-2025', 'bundestag-fraktionen-2026'],
    asOf: PARTY_CONTENT_AS_OF,
  },
  {
    schemaVersion: 1,
    id: 'fdp',
    abbreviation: 'FDP',
    name: 'Forum Demokratischer Perspektiven',
    color: '#f1cf3a',
    textColor: '#11171b',
    emblem: 'F',
    summary: 'Eine marktliberale Reformkraft für Unternehmertum, digitale Verwaltung und fiskalische Begrenzung.',
    strengths: ['Unternehmensdynamik', 'Verwaltungsmodernisierung'],
    tradeoffs: ['Kleiner Ratseinfluss', 'Begrenzte soziale Puffer'],
    focusPriorityIds: ['employment', 'fiscalHealth', 'mobility'],
    policyPositions: [
      { policyId: 'business-tax-balance', stance: 'support', rationale: 'Die befristete Entlastung entspricht dem Schwerpunkt auf Wachstum, Investitionen und geringerer Belastung.', sourceIds: ['fdp-program-2025'] },
      { policyId: 'fdp-permits-30-days', stance: 'support', rationale: 'Genehmigungsfiktion und Verfahrensbeschleunigung sind ausdrückliche Programmforderungen.', sourceIds: ['fdp-program-2025'] },
      { policyId: 'fdp-holdings-review', stance: 'support', rationale: 'Die Prüfung kommunaler Beteiligungen auf Zweck und Rendite folgt der ordnungspolitischen Linie.', sourceIds: ['fdp-program-2025'] },
      { policyId: 'fdp-no-new-posts', stance: 'support', rationale: 'Die Bindung neuer Stellen an Gegenfinanzierung entspricht dem Programmschwerpunkt Haushaltsdisziplin.', sourceIds: ['fdp-program-2025'] },
      { policyId: 'shared-consolidation', stance: 'support', rationale: 'Konsolidierung ist eine ausdrückliche haushaltspolitische Programmforderung.', sourceIds: ['fdp-program-2025'] },
      { policyId: 'shared-maintenance', stance: 'conditional', rationale: 'Werterhalt ja, aber als dauerhafte Ausgabenbindung nur mit Gegenfinanzierung.', sourceIds: ['fdp-program-2025'] },
      { policyId: 'shared-block-renewal', stance: 'conditional', rationale: 'Die Kommune saniert, was ihr gehört; für private Blöcke braucht es Anreize statt Programme.', sourceIds: ['fdp-program-2025'] },
    ],
    axes: { fiscalRestraint: 0.8, marketVsPublic: 0.9, growthVsPreservation: -0.1, climateAmbition: 0, redistribution: -0.6, securityAuthority: 0, opennessIntegration: 0.3 },
    redLines: [{ axis: 'fiscalRestraint', operator: '<', value: -0.7, reason: 'Dauerhaft schuldenfinanzierte Ausgabenprogramme werden abgelehnt.' }],
    stats: { councilSeats: 3, publicSupport: 5, organization: 52, negotiation: 66 },
    sourceIds: ['fdp-program-2025', 'federal-election-result-2025'],
    asOf: PARTY_CONTENT_AS_OF,
  },
]

export function getParty(partyId: PartyId): PartyDefinition {
  const party = PARTIES.find(({ id }) => id === partyId)
  if (!party)
    throw new Error(`Unknown party: ${partyId}`)
  return party
}

/**
 * Build a value for every council party. The object literal is typed as a complete
 * `Record<PartyId, T>`, so adding a party to `PartyId` fails to compile until it is handled here —
 * which is what keeps seat maps and vote tallies exhaustive without a cast.
 */
export function mapParties<T>(select: (party: PartyDefinition) => T): Record<PartyId, T> {
  return {
    cdu: select(getParty('cdu')),
    afd: select(getParty('afd')),
    spd: select(getParty('spd')),
    gruene: select(getParty('gruene')),
    linke: select(getParty('linke')),
    fdp: select(getParty('fdp')),
  }
}

export function getPartyEvidence(sourceIds: string[]): EvidenceReference[] {
  return sourceIds.flatMap((sourceId) => {
    const source = PARTY_EVIDENCE.find(({ id }) => id === sourceId)
    return source ? [source] : []
  })
}
