import type { EvidenceReference, PartyId, PolicyDefinition } from '../core/contracts'

export const EVIDENCE: EvidenceReference[] = [
  {
    id: 'vertical-slice-model-v1',
    publisher: '2036 Simulation Lab',
    title: 'Vertical-Slice-Modellannahmen',
    url: '/docs/DATA_SOURCES.md',
    publishedAt: '2026-09-11',
    accessedAt: '2026-09-11',
    claimType: 'effect',
    applicability: 'Fiktive Modellwerte für den spielbaren Prototyp; keine reale Prognose.',
  },
]

export const POLICIES: PolicyDefinition[] = [
  {
    id: 'housing-accelerator',
    name: 'Wohnungsbau-Turbo',
    partyIds: ['spd'],
    summary: 'Mehr kommunaler Wohnungsbau und schnellere Genehmigungen entlasten den Markt – mit hoher Anfangsinvestition.',
    category: 'housing',
    jurisdiction: 'municipal',
    implementationCost: 28,
    monthlyCost: 1.4,
    // Ein Bauprogramm über sechs Jahre. Die Wohnungen bleiben, das Programm läuft aus.
    costMonths: 72,
    administrativeLoad: 22,
    axes: { growthVsPreservation: -0.6, marketVsPublic: -0.6, redistribution: 0.5, fiscalRestraint: -0.6 },
    salience: { growthVsPreservation: 0.9, marketVsPublic: 0.8, redistribution: 0.6, fiscalRestraint: 0.9 },
    effects: [
      // Buys construction starts, not finished flats: the pipeline needs ~22 months to deliver.
      { target: 'unitsUnderConstruction', mode: 'rate', delayMonths: 2, rampMonths: 10, min: 55, expected: 110, max: 150, confidence: 'medium' },
      { target: 'socialUnits', mode: 'level', delayMonths: 20, rampMonths: 16, min: 240, expected: 480, max: 700, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'transit-network',
    name: 'LindenTakt 2030',
    partyIds: ['gruene'],
    summary: 'Dichterer Takt, neue Busachsen und Vorrangschaltungen verbessern Erreichbarkeit und Luftqualität.',
    category: 'mobility',
    jurisdiction: 'municipal',
    implementationCost: 19,
    monthlyCost: 1.9,
    administrativeLoad: 18,
    axes: { climateAmbition: 0.6, marketVsPublic: -0.5, fiscalRestraint: -0.4, growthVsPreservation: -0.2 },
    salience: { climateAmbition: 0.9, marketVsPublic: 0.6, fiscalRestraint: 0.8 },
    effects: [
      { target: 'transitCapacity', mode: 'level', delayMonths: 1, rampMonths: 14, min: 7, expected: 12, max: 16, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'business-tax-balance',
    name: 'Gewerbesteuer-Pakt',
    partyIds: ['fdp'],
    summary: 'Fünf Jahre niedrigerer Hebesatz sollen Ansiedlungen auslösen. Die Betriebe bleiben, die Senkung läuft aus.',
    category: 'finance',
    jurisdiction: 'municipal',
    implementationCost: 4,
    // Ein Hebesatz von 450 auf 400 Punkte kostet gut ein Zehntel eines Aufkommens von rund
    // 133 Mio. € im Jahr. Fünf Jahre lang; was in dieser Zeit angesiedelt wurde, zahlt danach voll.
    monthlyCost: 1.2,
    costMonths: 60,
    administrativeLoad: 8,
    axes: { marketVsPublic: 0.7, fiscalRestraint: 0.2, redistribution: -0.5 },
    salience: { marketVsPublic: 0.9, redistribution: 0.7, fiscalRestraint: 0.7 },
    effects: [
      { target: 'businessSites', mode: 'level', delayMonths: 4, rampMonths: 18, min: 180, expected: 420, max: 700, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'cdu-commercial-land',
    name: 'Gewerbeflächen-Offensive',
    partyIds: ['cdu'],
    summary: 'Drei Bebauungspläne im Eilverfahren, Erschließung auf Vorrat. Wer ansiedeln will, soll nicht zwei Jahre warten.',
    category: 'economy',
    jurisdiction: 'municipal',
    implementationCost: 9.5,
    monthlyCost: 0.22,
    costMonths: 60,
    administrativeLoad: 7,
    axes: { marketVsPublic: 0.6, growthVsPreservation: -0.5, fiscalRestraint: -0.2 },
    salience: { marketVsPublic: 0.8, growthVsPreservation: 0.7 },
    effects: [
      { target: 'businessSites', mode: 'level', delayMonths: 8, rampMonths: 20, min: 186.0, expected: 310, max: 434.0, confidence: 'medium' },
      { target: 'greenSpaceHectares', mode: 'level', delayMonths: 10, rampMonths: 12, min: -5.4, expected: -9, max: -12.6, confidence: 'high' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'cdu-order-service',
    name: 'Ordnungsdienst rund um die Uhr',
    partyIds: ['cdu'],
    summary: 'Der kommunale Ordnungsdienst bekommt Nachtschichten und eine feste Präsenz an den Brennpunkten.',
    category: 'safety',
    jurisdiction: 'municipal',
    implementationCost: 2.4,
    monthlyCost: 0.64,
    administrativeLoad: 6,
    axes: { securityAuthority: 0.7, fiscalRestraint: -0.2, redistribution: -0.1 },
    salience: { securityAuthority: 1, fiscalRestraint: 0.5 },
    effects: [
      { target: 'orderServiceFte', mode: 'level', delayMonths: 2, rampMonths: 8, min: 13.2, expected: 22, max: 30.8, confidence: 'high' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'cdu-family-land',
    name: 'Baulandmodell für Familien',
    partyIds: ['cdu'],
    summary: 'Städtische Grundstücke zum Festpreis an Familien mit Ortsbezug, mit Bauverpflichtung binnen drei Jahren.',
    category: 'housing',
    jurisdiction: 'municipal',
    implementationCost: 6.8,
    monthlyCost: 0.12,
    costMonths: 84,
    administrativeLoad: 6,
    axes: { marketVsPublic: 0.5, redistribution: -0.2, growthVsPreservation: -0.3 },
    salience: { marketVsPublic: 0.7, redistribution: 0.6 },
    effects: [
      { target: 'housingUnits', mode: 'level', delayMonths: 14, rampMonths: 18, min: 168.0, expected: 280, max: 392.0, confidence: 'medium' },
      { target: 'unitsUnderConstruction', mode: 'level', delayMonths: 6, rampMonths: 10, min: 96.0, expected: 160, max: 224.0, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'cdu-debt-brake',
    name: 'Schuldenbremse in der Hauptsatzung',
    partyIds: ['cdu'],
    summary: 'Neue Dauerkosten nur mit benannter Gegenfinanzierung. Bindet den Rat an das, was er beschließt.',
    category: 'finance',
    jurisdiction: 'municipal',
    implementationCost: 0.4,
    monthlyCost: -0.55,
    administrativeLoad: 4,
    axes: { fiscalRestraint: 0.9, marketVsPublic: 0.3, redistribution: -0.4 },
    salience: { fiscalRestraint: 1, redistribution: 0.6 },
    effects: [
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 6, rampMonths: 18, min: 0.072, expected: 0.12, max: 0.168, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'afd-cctv-network',
    name: 'Kameranetz an allen Knotenpunkten',
    partyIds: ['afd'],
    summary: 'Vierzig zusätzliche Standorte mit Aufzeichnung, ausgewertet durch eine eigene Leitstelle.',
    category: 'safety',
    jurisdiction: 'municipal',
    implementationCost: 5.6,
    monthlyCost: 0.48,
    administrativeLoad: 7,
    axes: { securityAuthority: 0.9, opennessIntegration: -0.4, fiscalRestraint: -0.2 },
    salience: { securityAuthority: 1, opennessIntegration: 0.6 },
    effects: [
      { target: 'orderServiceFte', mode: 'level', delayMonths: 4, rampMonths: 10, min: 9.6, expected: 16, max: 22.4, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'afd-townscape',
    name: 'Ortsbildsatzung',
    partyIds: ['afd'],
    summary: 'Neubau nur im Maßstab des Bestands, keine Geschosse über die Traufhöhe. Das gewachsene Stadtbild bleibt.',
    category: 'housing',
    jurisdiction: 'municipal',
    implementationCost: 0.6,
    monthlyCost: 0.09,
    costMonths: 96,
    administrativeLoad: 5,
    axes: { growthVsPreservation: 0.8, marketVsPublic: -0.3, climateAmbition: -0.2 },
    salience: { growthVsPreservation: 1, marketVsPublic: 0.5 },
    effects: [
      { target: 'housingUnits', mode: 'level', delayMonths: 8, rampMonths: 20, min: -108.0, expected: -180, max: -252.0, confidence: 'medium' },
      { target: 'greenSpaceHectares', mode: 'level', delayMonths: 10, rampMonths: 16, min: 4.2, expected: 7, max: 9.8, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'afd-roads-first',
    name: 'Straßenunterhalt vor Klimastellen',
    partyIds: ['afd'],
    summary: 'Die Mittel der Klimaschutzagentur gehen in Fahrbahndecken und Brückenprüfungen.',
    category: 'mobility',
    jurisdiction: 'municipal',
    implementationCost: 1.2,
    monthlyCost: 0.26,
    costMonths: 72,
    administrativeLoad: 5,
    axes: { climateAmbition: -0.8, fiscalRestraint: 0.4, growthVsPreservation: 0.2 },
    salience: { climateAmbition: 1, fiscalRestraint: 0.6 },
    effects: [
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 2, rampMonths: 10, min: 0.252, expected: 0.42, max: 0.588, confidence: 'high' },
      { target: 'cleanHeat', mode: 'level', delayMonths: 6, rampMonths: 14, min: -8.4, expected: -14, max: -19.6, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'afd-referendum',
    name: 'Bürgerentscheid über Großvorhaben',
    partyIds: ['afd'],
    summary: 'Jedes Vorhaben über zwanzig Millionen geht vor den Bürgerentscheid. Der Rat entscheidet nicht mehr allein.',
    category: 'governance',
    jurisdiction: 'municipal',
    implementationCost: 1.8,
    monthlyCost: 0.14,
    costMonths: 84,
    administrativeLoad: 6,
    axes: { opennessIntegration: 0.2, marketVsPublic: -0.2, growthVsPreservation: 0.5, fiscalRestraint: 0.3 },
    salience: { growthVsPreservation: 0.7, fiscalRestraint: 0.5 },
    effects: [
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 8, rampMonths: 16, min: -0.048, expected: -0.08, max: -0.112, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'spd-training-guarantee',
    name: 'Kommunale Ausbildungsgarantie',
    partyIds: ['spd'],
    summary: 'Wer keinen Platz findet, bekommt einen bei der Stadt oder einem Träger. Dreihundert Plätze im Jahr.',
    category: 'social',
    jurisdiction: 'municipal',
    implementationCost: 3.2,
    monthlyCost: 0.52,
    administrativeLoad: 7,
    axes: { redistribution: 0.8, marketVsPublic: -0.6, opennessIntegration: 0.4 },
    salience: { redistribution: 1, marketVsPublic: 0.6 },
    effects: [
      { target: 'integrationPlaces', mode: 'level', delayMonths: 4, rampMonths: 12, min: 114.0, expected: 190, max: 266.0, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'spd-social-ticket',
    name: 'Sozialticket im Nahverkehr',
    partyIds: ['spd'],
    summary: 'Neunundzwanzig Euro für alle mit Berechtigungsschein. Die Stadt gleicht den Fehlbetrag aus.',
    category: 'mobility',
    jurisdiction: 'municipal',
    implementationCost: 0.8,
    monthlyCost: 0.58,
    administrativeLoad: 5,
    axes: { redistribution: 0.8, marketVsPublic: -0.5, climateAmbition: 0.3 },
    salience: { redistribution: 1, marketVsPublic: 0.5, climateAmbition: 0.4 },
    effects: [
      { target: 'transitCapacity', mode: 'level', delayMonths: 3, rampMonths: 10, min: 1.68, expected: 2.8, max: 3.92, confidence: 'high' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'spd-procurement',
    name: 'Tariftreue bei allen Vergaben',
    partyIds: ['spd'],
    summary: 'Wer für die Stadt baut oder reinigt, zahlt Tarif. Die Angebote werden teurer, die Fluktuation sinkt.',
    category: 'governance',
    jurisdiction: 'municipal',
    implementationCost: 0.7,
    monthlyCost: 0.34,
    administrativeLoad: 6,
    axes: { redistribution: 0.8, marketVsPublic: -0.7, fiscalRestraint: -0.4 },
    salience: { redistribution: 1, marketVsPublic: 0.9 },
    effects: [
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 6, rampMonths: 14, min: 0.096, expected: 0.16, max: 0.224, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'gruene-cycle-network',
    name: 'Radnetz in einem Zug',
    partyIds: ['gruene'],
    summary: 'Zweiundzwanzig Kilometer geschützte Radwege, nicht in Abschnitten, sondern als Netz.',
    category: 'mobility',
    jurisdiction: 'municipal',
    implementationCost: 12.5,
    monthlyCost: 0.24,
    costMonths: 72,
    administrativeLoad: 7,
    axes: { climateAmbition: 0.8, growthVsPreservation: 0.3, marketVsPublic: -0.3 },
    salience: { climateAmbition: 1, growthVsPreservation: 0.5 },
    effects: [
      { target: 'transitCapacity', mode: 'level', delayMonths: 6, rampMonths: 20, min: 2.52, expected: 4.2, max: 5.88, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'gruene-heat-plan',
    name: 'Kommunale Wärmeplanung umsetzen',
    partyIds: ['gruene'],
    summary: 'Quartiersnetze statt Einzelheizungen, mit Anschlussrecht und Förderung für die ersten drei Viertel.',
    category: 'environment',
    jurisdiction: 'municipal',
    implementationCost: 17,
    monthlyCost: 0.38,
    costMonths: 60,
    administrativeLoad: 8,
    axes: { climateAmbition: 0.9, marketVsPublic: -0.6, fiscalRestraint: -0.5 },
    salience: { climateAmbition: 1, marketVsPublic: 0.7, fiscalRestraint: 0.6 },
    effects: [
      { target: 'cleanHeat', mode: 'level', delayMonths: 10, rampMonths: 24, min: 31.2, expected: 52, max: 72.8, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'gruene-unsealing',
    name: 'Schwammstadt-Programm',
    partyIds: ['gruene'],
    summary: 'Höfe, Parkplätze und Schulhöfe entsiegeln, Regen versickert wieder statt in die Kanäle zu schießen.',
    category: 'environment',
    jurisdiction: 'municipal',
    implementationCost: 7.4,
    monthlyCost: 0.19,
    costMonths: 84,
    administrativeLoad: 6,
    axes: { climateAmbition: 0.8, growthVsPreservation: 0.6, marketVsPublic: -0.3 },
    salience: { climateAmbition: 1, growthVsPreservation: 0.7 },
    effects: [
      { target: 'greenSpaceHectares', mode: 'level', delayMonths: 6, rampMonths: 20, min: 12.6, expected: 21, max: 29.4, confidence: 'medium' },
      { target: 'investmentBacklog', mode: 'level', delayMonths: 12, rampMonths: 20, min: -7.2, expected: -12, max: -16.8, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'linke-buy-back',
    name: 'Bestand zurückkaufen',
    partyIds: ['linke'],
    summary: 'Die Stadt kauft, wo Portfolios wechseln, und bindet die Mieten dauerhaft. Teuer heute, gebunden für immer.',
    category: 'housing',
    jurisdiction: 'municipal',
    implementationCost: 22,
    monthlyCost: 0.44,
    costMonths: 96,
    administrativeLoad: 8,
    axes: { marketVsPublic: -0.9, redistribution: 0.9, fiscalRestraint: -0.7 },
    salience: { marketVsPublic: 1, redistribution: 1, fiscalRestraint: 0.8 },
    effects: [
      { target: 'socialUnits', mode: 'level', delayMonths: 10, rampMonths: 24, min: 312.0, expected: 520, max: 728.0, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'linke-free-transit',
    name: 'Fahrscheinloser Nahverkehr in Etappen',
    partyIds: ['linke'],
    summary: 'Erst Schüler und Rentner, dann alle. Die Einnahmen fallen weg, die Fahrten steigen sprunghaft.',
    category: 'mobility',
    jurisdiction: 'municipal',
    implementationCost: 2.6,
    monthlyCost: 1.15,
    administrativeLoad: 7,
    axes: { marketVsPublic: -0.9, redistribution: 0.9, climateAmbition: 0.6 },
    salience: { marketVsPublic: 1, redistribution: 1, climateAmbition: 0.6 },
    effects: [
      { target: 'transitCapacity', mode: 'level', delayMonths: 4, rampMonths: 16, min: 3.84, expected: 6.4, max: 8.96, confidence: 'medium' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'linke-remunicipalise',
    name: 'Stadtwerke-Anteile zurückholen',
    partyIds: ['linke'],
    summary: 'Die verkauften 49 Prozent zurück in kommunale Hand. Die Rendite bleibt dann in der Stadt.',
    category: 'economy',
    jurisdiction: 'municipal',
    implementationCost: 34,
    monthlyCost: -0.42,
    administrativeLoad: 8,
    axes: { marketVsPublic: -0.9, redistribution: 0.6, fiscalRestraint: -0.6, climateAmbition: 0.4 },
    salience: { marketVsPublic: 1, fiscalRestraint: 0.8, redistribution: 0.6 },
    effects: [
      { target: 'cleanHeat', mode: 'level', delayMonths: 12, rampMonths: 24, min: 14.4, expected: 24, max: 33.6, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'linke-employment-company',
    name: 'Kommunale Beschäftigungsgesellschaft',
    partyIds: ['linke'],
    summary: 'Sozialversicherte Stellen für Langzeitarbeitslose in Grünpflege, Quartiersarbeit und Reparatur.',
    category: 'social',
    jurisdiction: 'municipal',
    implementationCost: 2.2,
    monthlyCost: 0.68,
    administrativeLoad: 7,
    axes: { redistribution: 0.9, marketVsPublic: -0.8, fiscalRestraint: -0.5 },
    salience: { redistribution: 1, marketVsPublic: 0.8 },
    effects: [
      { target: 'integrationPlaces', mode: 'level', delayMonths: 4, rampMonths: 12, min: 90.0, expected: 150, max: 210.0, confidence: 'medium' },
      { target: 'greenSpaceHectares', mode: 'level', delayMonths: 8, rampMonths: 16, min: 3.0, expected: 5, max: 7.0, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'fdp-permits-30-days',
    name: 'Genehmigung in dreißig Tagen',
    partyIds: ['fdp'],
    summary: 'Digitale Bauakte, Fristenlauf mit Genehmigungsfiktion. Wer nicht entscheidet, hat zugestimmt.',
    category: 'economy',
    jurisdiction: 'municipal',
    implementationCost: 5.2,
    monthlyCost: 0.28,
    costMonths: 48,
    administrativeLoad: 6,
    axes: { marketVsPublic: 0.8, fiscalRestraint: 0.2, growthVsPreservation: -0.4 },
    salience: { marketVsPublic: 1, growthVsPreservation: 0.6 },
    effects: [
      { target: 'businessSites', mode: 'level', delayMonths: 8, rampMonths: 16, min: 132.0, expected: 220, max: 308.0, confidence: 'medium' },
      { target: 'unitsUnderConstruction', mode: 'level', delayMonths: 6, rampMonths: 12, min: 84.0, expected: 140, max: 196.0, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'fdp-holdings-review',
    name: 'Beteiligungen auf den Prüfstand',
    partyIds: ['fdp'],
    summary: 'Vierzehn städtische Gesellschaften, geprüft auf Zweck und Rendite. Was der Markt kann, geht an den Markt.',
    category: 'finance',
    jurisdiction: 'municipal',
    implementationCost: 1.6,
    monthlyCost: -0.78,
    administrativeLoad: 7,
    axes: { marketVsPublic: 0.9, fiscalRestraint: 0.8, redistribution: -0.6 },
    salience: { marketVsPublic: 1, fiscalRestraint: 0.9, redistribution: 0.7 },
    effects: [
      { target: 'socialUnits', mode: 'level', delayMonths: 14, rampMonths: 20, min: -96.0, expected: -160, max: -224.0, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'fdp-no-new-posts',
    name: 'Keine neue Stelle ohne Gegenfinanzierung',
    partyIds: ['fdp'],
    summary: 'Jede zusätzliche Dauerstelle braucht eine benannte Einsparung. Der Apparat wächst nicht mehr von selbst.',
    category: 'governance',
    jurisdiction: 'municipal',
    implementationCost: 0.3,
    monthlyCost: -0.36,
    administrativeLoad: 4,
    axes: { fiscalRestraint: 0.9, marketVsPublic: 0.6, redistribution: -0.5 },
    salience: { fiscalRestraint: 1, marketVsPublic: 0.6 },
    effects: [
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 8, rampMonths: 16, min: -0.036, expected: -0.06, max: -0.084, confidence: 'low' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'shared-consolidation',
    name: 'Haushaltskonsolidierung',
    summary: 'Ein Prozent quer durch alle freiwilligen Leistungen, drei Jahre lang. Tut überall weh und rettet den Abschluss.',
    category: 'finance',
    jurisdiction: 'municipal',
    implementationCost: 0.8,
    monthlyCost: -1.45,
    costMonths: 36,
    administrativeLoad: 6,
    axes: { fiscalRestraint: 0.8, redistribution: -0.5, marketVsPublic: 0.3 },
    salience: { fiscalRestraint: 1, redistribution: 0.8 },
    effects: [
      { target: 'integrationPlaces', mode: 'level', delayMonths: 2, rampMonths: 10, min: -42.0, expected: -70, max: -98.0, confidence: 'high' },
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 2, rampMonths: 8, min: -0.06, expected: -0.1, max: -0.14, confidence: 'high' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
  {
    id: 'shared-maintenance',
    name: 'Instandhaltungsprogramm',
    summary: 'Der Unterhalt geht dauerhaft auf Bedarf. Nichts daran ist sichtbar, bis man es zehn Jahre unterlässt.',
    category: 'finance',
    jurisdiction: 'municipal',
    implementationCost: 3.4,
    monthlyCost: 0.85,
    administrativeLoad: 5,
    axes: { fiscalRestraint: -0.3, marketVsPublic: -0.2, growthVsPreservation: 0.3 },
    salience: { fiscalRestraint: 0.7, growthVsPreservation: 0.4 },
    effects: [
      { target: 'maintenanceSpend', mode: 'level', delayMonths: 2, rampMonths: 12, min: 0.54, expected: 0.9, max: 1.26, confidence: 'high' },
    ],
    sourceIds: ['vertical-slice-model-v1'],
  },
]

export function getPolicy(policyId: string): PolicyDefinition | undefined {
  return POLICIES.find(policy => policy.id === policyId)
}

/**
 * Das Programm einer Fraktion: was sie einbringen würde.
 *
 * Vier eigene Vorlagen je Partei und zwei, die jeder Rat irgendwann braucht. Vorher bekam jede
 * Partei dieselben drei, sodass die LINKE die Gewerbesteuersenkung einbringen konnte und die FDP den
 * kommunalen Wohnungsbau — nicht neutral, sondern inkohärent.
 *
 * Die Auswahl steht hier und nicht in der Simulation: dort wird gerechnet, hier wird ausgewählt.
 * Dieselbe Vorlage wirkt bei jedem identisch, sie wird nur nicht jedem angeboten.
 */
export function policiesFor(partyId: PartyId | null): PolicyDefinition[] {
  return POLICIES.filter(policy => !policy.partyIds || (partyId !== null && policy.partyIds.includes(partyId)))
}

/** Ob diese Fraktion das überhaupt einbringen kann. */
export function mayTable(partyId: PartyId | null, policyId: string): boolean {
  const policy = getPolicy(policyId)
  return policy !== undefined && (!policy.partyIds || (partyId !== null && policy.partyIds.includes(partyId)))
}
