import type { EventDefinition, PolicyEffect } from '../core/contracts'

/**
 * The Lindenhafen event library. See docs/EVENT_MATRIX.md for the authoring rules.
 *
 * Two rules are load-bearing:
 *  - Options buy capacity, never outcomes. A safety measure staffs the Ordnungsdienst; it does not
 *    set a crime rate. The dynamics turn capacity into outcomes with the appropriate lag.
 *  - No trigger reads an identity-composition indicator. Contested causality runs through funded
 *    capacity, per the rule in docs/METRICS.md and AGENTS.md.
 *
 * All values are labelled Lindenhafen model assumptions, not real-world forecasts.
 */

const MODEL = ['vertical-slice-model-v1']

type EffectInput = Partial<PolicyEffect> & Pick<PolicyEffect, 'target' | 'expected'>

const effect = (input: EffectInput): PolicyEffect => ({
  mode: 'level',
  delayMonths: 2,
  rampMonths: 10,
  min: input.expected * 0.55,
  max: input.expected * 1.45,
  confidence: 'medium',
  ...input,
})

export const EVENTS: EventDefinition[] = [
  // --- Safety --------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'saf-burglary-series',
    kind: 'decision',
    category: 'safety',
    title: 'Einbruchserie im Wohnring Süd',
    briefing:
      'Seit zwei Monaten häufen sich Wohnungseinbrüche im Wohnring Süd. Die Polizei ist Landessache, die Stadt kann über Ordnungsdienst, Beleuchtung und Prävention entscheiden.',
    urgency: 'important',
    trigger: { earliestMonth: 4, latestMonth: 120, conditions: [{ metric: 'burglaryRate', operator: '>', value: 4.1, sustainedMonths: 2 }], baseWeight: 10, cooldownMonths: 18, oncePerCampaign: false },
    immediateEffects: [],
    defaultOptionId: 'saf-burglary-none',
    expiresInMonths: 3,
    options: [
      {
        id: 'saf-burglary-order',
        label: 'Ordnungsdienst aufstocken',
        rationale: 'Zwölf zusätzliche Stellen und Nachtstreifen im betroffenen Quartier.',
        oneOffCost: 2.4, monthlyCost: 0.72,
        axes: { securityAuthority: 0.7, fiscalRestraint: -0.2, marketVsPublic: -0.3 },
        salience: { securityAuthority: 1, fiscalRestraint: 0.5, marketVsPublic: 0.2 },
        effects: [effect({ target: 'orderServiceFte', expected: 14, rampMonths: 8 })],
        sourceIds: MODEL,
      },
      {
        id: 'saf-burglary-prevention',
        label: 'Beleuchtung und Nachbarschaftsprogramm',
        rationale: 'Straßenbeleuchtung, Quartiersmanagement und Jugendarbeit statt Präsenz.',
        oneOffCost: 3.6, monthlyCost: 0.38,
        axes: { securityAuthority: -0.5, redistribution: 0.4, marketVsPublic: -0.4 },
        salience: { securityAuthority: 1, redistribution: 0.6, marketVsPublic: 0.3 },
        effects: [
          effect({ target: 'orderServiceFte', expected: 5, rampMonths: 10 }),
          effect({ target: 'integrationPlaces', expected: 120, rampMonths: 14, confidence: 'low' }),
        ],
        sourceIds: MODEL,
      },
      {
        id: 'saf-burglary-cctv',
        label: 'Videoüberwachung an Knotenpunkten',
        rationale: 'Kameras an 18 Knotenpunkten, schnell umsetzbar, rechtlich umstritten.',
        oneOffCost: 5.1, monthlyCost: 0.24,
        axes: { securityAuthority: 0.9, marketVsPublic: 0.4, opennessIntegration: -0.3 },
        salience: { securityAuthority: 1, marketVsPublic: 0.4, opennessIntegration: 0.5 },
        effects: [effect({ target: 'orderServiceFte', expected: 8, rampMonths: 5, confidence: 'low' })],
        sourceIds: MODEL,
      },
      {
        id: 'saf-burglary-none',
        label: 'Zur Kenntnis nehmen',
        rationale: 'Die Verwaltung verweist auf die Zuständigkeit des Landes.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { fiscalRestraint: 0.8 },
        salience: { fiscalRestraint: 1, securityAuthority: 0.3 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'saf-youth-centre',
    kind: 'decision',
    category: 'social',
    title: 'Jugendtreff vor der Schließung',
    briefing:
      'Der freie Träger des Jugendtreffs Hafenstraße kann die Kofinanzierung nicht mehr aufbringen. Die Einrichtung erreicht rund 400 Jugendliche.',
    urgency: 'normal',
    trigger: { earliestMonth: 8, latestMonth: 110, conditions: [{ metric: 'cityBudget', operator: '<', value: 300 }], baseWeight: 7, cooldownMonths: 36, oncePerCampaign: true },
    immediateEffects: [],
    defaultOptionId: 'saf-youth-close',
    expiresInMonths: 2,
    options: [
      {
        id: 'saf-youth-fund',
        label: 'Weiterfinanzieren',
        rationale: 'Die Stadt übernimmt den Fehlbetrag dauerhaft.',
        oneOffCost: 0.4, monthlyCost: 0.21,
        axes: { redistribution: 0.6, marketVsPublic: -0.5, fiscalRestraint: -0.4 },
        salience: { redistribution: 1, marketVsPublic: 0.5, fiscalRestraint: 0.7 },
        effects: [effect({ target: 'integrationPlaces', expected: 90, rampMonths: 6 })],
        sourceIds: MODEL,
      },
      {
        id: 'saf-youth-transfer',
        label: 'Trägerwechsel ausschreiben',
        rationale: 'Günstiger, aber mit Übergangslücke und Personalwechsel.',
        oneOffCost: 0.2, monthlyCost: 0.09,
        axes: { marketVsPublic: 0.5, fiscalRestraint: 0.4 },
        salience: { marketVsPublic: 1, fiscalRestraint: 0.8, redistribution: 0.3 },
        effects: [effect({ target: 'integrationPlaces', expected: 40, delayMonths: 6, rampMonths: 8, confidence: 'low' })],
        sourceIds: MODEL,
      },
      {
        id: 'saf-youth-close',
        label: 'Schließen',
        rationale: 'Spart sofort. Die Folgen erscheinen erst Jahre später in der Jugendarbeitslosigkeit.',
        oneOffCost: 0, monthlyCost: -0.12,
        axes: { fiscalRestraint: 0.9, redistribution: -0.5, marketVsPublic: 0.3 },
        salience: { fiscalRestraint: 1, redistribution: 0.8 },
        effects: [effect({ target: 'integrationPlaces', expected: -70, delayMonths: 1, rampMonths: 4 })],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },

  // --- Housing -------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'hou-investor-block',
    kind: 'decision',
    category: 'housing',
    title: 'Investor kauft 400 Wohnungen',
    briefing:
      'Ein überregionaler Bestandshalter übernimmt 412 Wohnungen in Gründerzeit-Nord. Die Stadt hat ein Vorkaufsrecht, aber nur acht Wochen Zeit.',
    urgency: 'breaking',
    trigger: { earliestMonth: 6, latestMonth: 96, conditions: [{ metric: 'vacantUnits', operator: '<', value: 3_000 }], baseWeight: 12, cooldownMonths: 40, oncePerCampaign: true },
    immediateEffects: [],
    defaultOptionId: 'hou-investor-none',
    expiresInMonths: 2,
    options: [
      {
        id: 'hou-investor-preempt',
        label: 'Vorkaufsrecht ziehen',
        rationale: 'Teuer und sofort kassenwirksam, sichert aber 412 Wohnungen dauerhaft preisgebunden.',
        oneOffCost: 34, monthlyCost: 0.6,
        axes: { marketVsPublic: -0.9, redistribution: 0.7, fiscalRestraint: -0.7 },
        salience: { marketVsPublic: 1, redistribution: 0.8, fiscalRestraint: 0.9 },
        effects: [effect({ target: 'socialUnits', expected: 412, delayMonths: 1, rampMonths: 4, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'hou-investor-charter',
        label: 'Sozialcharta verhandeln',
        rationale: 'Kostenlos, aber freiwillig: Mieterschutz für zehn Jahre ohne dauerhafte Bindung.',
        oneOffCost: 0.6, monthlyCost: 0,
        axes: { marketVsPublic: 0, redistribution: 0.3, fiscalRestraint: 0.3 },
        salience: { marketVsPublic: 0.7, redistribution: 0.7, fiscalRestraint: 0.5 },
        effects: [effect({ target: 'socialUnits', expected: 150, delayMonths: 2, rampMonths: 8, confidence: 'low' })],
        sourceIds: MODEL,
      },
      {
        id: 'hou-investor-none',
        label: 'Verkauf laufen lassen',
        rationale: 'Kein Eingriff in den Markt, keine Belastung des Haushalts.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { marketVsPublic: 0.8, fiscalRestraint: 0.7, redistribution: -0.4 },
        salience: { marketVsPublic: 1, fiscalRestraint: 0.7, redistribution: 0.6 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'hou-bindings-expire',
    kind: 'milestone',
    category: 'housing',
    title: 'Sozialbindungen laufen aus',
    briefing:
      'Zum Jahreswechsel fallen erneut rund 900 Wohnungen aus der Preisbindung. Ohne Beschluss wird der Verlust dauerhaft.',
    urgency: 'important',
    trigger: { earliestMonth: 24, latestMonth: 120, conditions: [], baseWeight: 100, cooldownMonths: 46, oncePerCampaign: false, scheduledMonthOfYear: 1 },
    immediateEffects: [],
    defaultOptionId: 'hou-bindings-none',
    expiresInMonths: 3,
    options: [
      {
        id: 'hou-bindings-buy',
        label: 'Bindungen ankaufen',
        rationale: 'Die Stadt kauft Belegungsrechte für weitere 20 Jahre zurück.',
        oneOffCost: 14, monthlyCost: 0.34,
        axes: { marketVsPublic: -0.7, redistribution: 0.7, fiscalRestraint: -0.5 },
        salience: { marketVsPublic: 0.9, redistribution: 1, fiscalRestraint: 0.8 },
        effects: [effect({ target: 'socialUnits', expected: 860, delayMonths: 1, rampMonths: 6, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'hou-bindings-build',
        label: 'Neubau binden statt Bestand kaufen',
        rationale: 'Günstiger pro Wohnung, wirkt aber erst nach der Bauzeit.',
        oneOffCost: 9, monthlyCost: 0.5,
        axes: { growthVsPreservation: -0.6, marketVsPublic: -0.4, redistribution: 0.5 },
        salience: { growthVsPreservation: 0.8, marketVsPublic: 0.6, redistribution: 0.8, fiscalRestraint: 0.5 },
        effects: [
          effect({ target: 'unitsUnderConstruction', mode: 'rate', expected: 42, delayMonths: 3, rampMonths: 10 }),
          effect({ target: 'socialUnits', expected: 320, delayMonths: 22, rampMonths: 12, confidence: 'medium' }),
        ],
        sourceIds: MODEL,
      },
      {
        id: 'hou-bindings-none',
        label: 'Auslaufen lassen',
        rationale: 'Keine Kosten. Der gebundene Bestand schrumpft dauerhaft.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { marketVsPublic: 0.7, fiscalRestraint: 0.8 },
        salience: { marketVsPublic: 0.8, fiscalRestraint: 1, redistribution: 0.6 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'hou-rent-shock',
    kind: 'incident',
    category: 'housing',
    title: 'Mietspiegel springt nach oben',
    briefing: 'Der neue Mietspiegel weist den stärksten Anstieg seit zwölf Jahren aus. Mieterinitiativen kündigen Proteste an.',
    urgency: 'important',
    trigger: { earliestMonth: 10, latestMonth: 128, conditions: [{ metric: 'averageRent', operator: '>', value: 14 }], baseWeight: 8, cooldownMonths: 14, oncePerCampaign: false },
    immediateEffects: [],
    options: [],
    expiresInMonths: 0,
    sourceIds: MODEL,
  },

  // --- Social --------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'soc-childcare-gap',
    kind: 'decision',
    category: 'social',
    title: 'Klagen auf einen Kitaplatz',
    briefing:
      'Eltern klagen auf den Rechtsanspruch. Die Betreuungsquote liegt unter der gesetzlichen Vorgabe, und die Verwaltung rechnet mit weiteren Verfahren.',
    urgency: 'important',
    trigger: { earliestMonth: 6, latestMonth: 120, conditions: [{ metric: 'childcareCoverage', operator: '<', value: 93, sustainedMonths: 3 }], baseWeight: 11, cooldownMonths: 22, oncePerCampaign: false },
    immediateEffects: [],
    defaultOptionId: 'soc-childcare-litigate',
    expiresInMonths: 3,
    options: [
      {
        id: 'soc-childcare-build',
        label: 'Ausbauprogramm beschließen',
        rationale: 'Vier neue Einrichtungen und Personalgewinnung. Wirkt ab dem übernächsten Kitajahr.',
        oneOffCost: 17, monthlyCost: 0.95,
        axes: { marketVsPublic: -0.6, redistribution: 0.6, fiscalRestraint: -0.6 },
        salience: { marketVsPublic: 0.7, redistribution: 0.9, fiscalRestraint: 0.9 },
        effects: [effect({ target: 'childcarePlaces', expected: 640, delayMonths: 8, rampMonths: 16, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'soc-childcare-daycare',
        label: 'Tagespflege fördern',
        rationale: 'Schneller und billiger, deckt aber nur einen Teil des Bedarfs ab.',
        oneOffCost: 3.2, monthlyCost: 0.42,
        axes: { marketVsPublic: 0.4, fiscalRestraint: 0.3, redistribution: 0.2 },
        salience: { marketVsPublic: 0.8, fiscalRestraint: 0.8, redistribution: 0.5 },
        effects: [effect({ target: 'childcarePlaces', expected: 260, delayMonths: 3, rampMonths: 9 })],
        sourceIds: MODEL,
      },
      {
        id: 'soc-childcare-litigate',
        label: 'Verfahren führen',
        rationale: 'Die Stadt bestreitet die Ansprüche und wartet Urteile ab.',
        oneOffCost: 1.1, monthlyCost: 0.14,
        axes: { fiscalRestraint: 0.8, redistribution: -0.3 },
        salience: { fiscalRestraint: 1, redistribution: 0.7 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'soc-allocation',
    kind: 'decision',
    category: 'social',
    title: 'Land weist 600 Personen zu',
    briefing:
      'Die Bezirksregierung weist Lindenhafen 600 Personen zur Aufnahme zu. Die Zuweisung selbst ist nicht verhandelbar; Unterbringung, Sprachkurse und Vermittlung sind kommunale Entscheidungen.',
    urgency: 'important',
    trigger: { earliestMonth: 7, latestMonth: 120, conditions: [], baseWeight: 8, cooldownMonths: 20, oncePerCampaign: false },
    immediateEffects: [],
    defaultOptionId: 'soc-allocation-central',
    expiresInMonths: 2,
    options: [
      {
        id: 'soc-allocation-decentral',
        label: 'Dezentral unterbringen und Kurse ausbauen',
        rationale: 'Wohnungen im Bestand plus Sprach- und Vermittlungsplätze. Teurer, wirkt auf Arbeitsmarkt und Zusammenhalt.',
        oneOffCost: 8.4, monthlyCost: 0.86,
        axes: { opennessIntegration: 0.8, redistribution: 0.5, marketVsPublic: -0.4, fiscalRestraint: -0.5 },
        salience: { opennessIntegration: 1, redistribution: 0.6, fiscalRestraint: 0.7 },
        effects: [effect({ target: 'integrationPlaces', expected: 420, delayMonths: 2, rampMonths: 10, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'soc-allocation-central',
        label: 'Sammelunterkunft am Hafen',
        rationale: 'Schnell und günstig. Ohne Vermittlungsstruktur bleibt die Integrationskapazität knapp.',
        oneOffCost: 3.1, monthlyCost: 0.31,
        axes: { opennessIntegration: -0.2, fiscalRestraint: 0.5, marketVsPublic: 0.2 },
        salience: { opennessIntegration: 0.8, fiscalRestraint: 0.9 },
        effects: [effect({ target: 'integrationPlaces', expected: 60, delayMonths: 2, rampMonths: 6, confidence: 'medium' })],
        sourceIds: MODEL,
      },
      {
        id: 'soc-allocation-appeal',
        label: 'Zuweisung beklagen',
        rationale: 'Rechtsmittel gegen den Verteilbescheid. Die Personen kommen trotzdem, nur später und unvorbereitet.',
        oneOffCost: 1.4, monthlyCost: 0.08,
        axes: { opennessIntegration: -0.8, fiscalRestraint: 0.6, securityAuthority: 0.4 },
        salience: { opennessIntegration: 1, fiscalRestraint: 0.6, securityAuthority: 0.4 },
        effects: [effect({ target: 'integrationPlaces', expected: -80, delayMonths: 1, rampMonths: 5 })],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },

  // --- Mobility ------------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'mob-bridge-closure',
    kind: 'chain',
    category: 'mobility',
    title: 'Hafenbrücke gesperrt',
    briefing:
      'Die Prüfstatik stuft die Hafenbrücke herab. Die Sperrung trennt Gewerbe Ost vom Hafen und trifft den Wirtschaftsverkehr sofort.',
    urgency: 'breaking',
    trigger: { earliestMonth: 18, latestMonth: 126, conditions: [{ metric: 'investmentBacklog', operator: '>', value: 140 }], baseWeight: 30, cooldownMonths: 60, oncePerCampaign: true },
    immediateEffects: [effect({ target: 'businessStock', mode: 'level', expected: -180, delayMonths: 0, rampMonths: 2, confidence: 'high' })],
    defaultOptionId: 'mob-bridge-detour',
    expiresInMonths: 2,
    options: [
      {
        id: 'mob-bridge-rebuild',
        label: 'Vollsanierung beauftragen',
        rationale: 'Teuer und langwierig, beseitigt aber den Schaden und einen Teil des Sanierungsstaus.',
        oneOffCost: 48, monthlyCost: 1.1,
        axes: { fiscalRestraint: -0.8, marketVsPublic: -0.2, growthVsPreservation: -0.2 },
        salience: { fiscalRestraint: 1, marketVsPublic: 0.3 },
        effects: [
          effect({ target: 'investmentBacklog', mode: 'rate', expected: -1.4, delayMonths: 2, rampMonths: 10, confidence: 'high' }),
          effect({ target: 'businessStock', expected: 220, delayMonths: 20, rampMonths: 10 }),
        ],
        sourceIds: MODEL,
      },
      {
        id: 'mob-bridge-temporary',
        label: 'Behelfsbrücke aufstellen',
        rationale: 'Schnell befahrbar, hält rund acht Jahre und verschiebt das eigentliche Problem.',
        oneOffCost: 19, monthlyCost: 0.42,
        axes: { fiscalRestraint: 0.3, growthVsPreservation: 0 },
        salience: { fiscalRestraint: 1 },
        effects: [effect({ target: 'businessStock', expected: 150, delayMonths: 6, rampMonths: 8 })],
        sourceIds: MODEL,
      },
      {
        id: 'mob-bridge-detour',
        label: 'Dauerhafte Umleitung',
        rationale: 'Kostet nichts und bleibt als Standortnachteil im Gewerbegebiet bestehen.',
        oneOffCost: 0.8, monthlyCost: 0.05,
        axes: { fiscalRestraint: 0.9 },
        salience: { fiscalRestraint: 1, growthVsPreservation: 0.3 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'mob-bike-axis',
    kind: 'decision',
    category: 'mobility',
    title: 'Radachse gegen Parkplätze',
    briefing:
      'Die geplante Radachse durch die Innenstadt kostet 310 Stellplätze. Einzelhandel und Verkehrswende-Initiative stehen sich gegenüber.',
    urgency: 'normal',
    trigger: { earliestMonth: 12, latestMonth: 120, conditions: [{ metric: 'transitCoverage', operator: '>', value: 60 }], baseWeight: 6, cooldownMonths: 34, oncePerCampaign: true },
    immediateEffects: [],
    defaultOptionId: 'mob-bike-postpone',
    expiresInMonths: 3,
    options: [
      {
        id: 'mob-bike-full',
        label: 'Radachse vollständig bauen',
        rationale: 'Durchgehende Führung, spürbarer Effekt auf Emissionen, Konflikt mit dem Einzelhandel.',
        oneOffCost: 11, monthlyCost: 0.24,
        axes: { climateAmbition: 0.8, growthVsPreservation: -0.3, marketVsPublic: -0.3 },
        salience: { climateAmbition: 1, growthVsPreservation: 0.5, marketVsPublic: 0.4 },
        effects: [effect({ target: 'transitCapacity', expected: 4.5, delayMonths: 4, rampMonths: 12 })],
        sourceIds: MODEL,
      },
      {
        id: 'mob-bike-compromise',
        label: 'Kompromissvariante',
        rationale: 'Zwei Abschnitte, 120 Stellplätze bleiben. Halber Nutzen, halber Streit.',
        oneOffCost: 6.4, monthlyCost: 0.14,
        axes: { climateAmbition: 0.3, growthVsPreservation: 0, marketVsPublic: 0 },
        salience: { climateAmbition: 0.8, growthVsPreservation: 0.4 },
        effects: [effect({ target: 'transitCapacity', expected: 2, delayMonths: 4, rampMonths: 12 })],
        sourceIds: MODEL,
      },
      {
        id: 'mob-bike-postpone',
        label: 'Zurückstellen',
        rationale: 'Das Vorhaben wandert in die nächste Wahlperiode.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { climateAmbition: -0.5, fiscalRestraint: 0.7, growthVsPreservation: 0.4 },
        salience: { climateAmbition: 1, fiscalRestraint: 0.6 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'mob-federal-funding',
    kind: 'decision',
    category: 'mobility',
    title: 'Bund schreibt Takterhöhung aus',
    briefing:
      'Ein Bundesprogramm fördert Taktverdichtung mit 70 Prozent. Die Antragsfrist läuft in zwei Monaten ab, der Eigenanteil belastet den Haushalt.',
    urgency: 'important',
    trigger: { earliestMonth: 26, latestMonth: 72, conditions: [], baseWeight: 8, cooldownMonths: 60, oncePerCampaign: true },
    immediateEffects: [],
    defaultOptionId: 'mob-funding-skip',
    expiresInMonths: 2,
    options: [
      {
        id: 'mob-funding-apply',
        label: 'Antrag stellen',
        rationale: 'Eigenanteil 30 Prozent, dafür die größte Reichweitensteigerung des Jahrzehnts.',
        oneOffCost: 12.5, monthlyCost: 1.35,
        axes: { climateAmbition: 0.6, marketVsPublic: -0.5, fiscalRestraint: -0.4 },
        salience: { climateAmbition: 0.8, marketVsPublic: 0.5, fiscalRestraint: 0.8 },
        effects: [effect({ target: 'transitCapacity', expected: 11, delayMonths: 6, rampMonths: 18, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'mob-funding-skip',
        label: 'Verzichten',
        rationale: 'Kein Eigenanteil, keine Folgekosten, keine Verbesserung.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { fiscalRestraint: 0.9, climateAmbition: -0.3 },
        salience: { fiscalRestraint: 1, climateAmbition: 0.6 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },

  // --- Environment ---------------------------------------------------------
  {
    schemaVersion: 1,
    id: 'env-heat-summer',
    kind: 'external',
    category: 'environment',
    title: 'Hitzesommer belastet die Stadt',
    briefing:
      'Vierzehn Tropennächte in Folge. Wie hart es die Stadt trifft, entschied sich in den Jahren davor über Stadtgrün und Entsiegelung.',
    urgency: 'important',
    trigger: { earliestMonth: 18, latestMonth: 130, conditions: [], baseWeight: 5, cooldownMonths: 22, oncePerCampaign: false, scheduledMonthOfYear: 7 },
    immediateEffects: [],
    options: [],
    expiresInMonths: 0,
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'env-green-offensive',
    kind: 'decision',
    category: 'environment',
    title: 'Stadtgrün-Offensive gefordert',
    briefing:
      'Die Grünfläche pro Kopf ist unter den Zielwert gefallen. Ein Entsiegelungs- und Pflanzprogramm wirkt erst in Jahren, aber nur, wenn es jetzt beginnt.',
    urgency: 'normal',
    trigger: { earliestMonth: 10, latestMonth: 110, conditions: [{ metric: 'greenSpacePerCapita', operator: '<', value: 21.4 }], baseWeight: 7, cooldownMonths: 24, oncePerCampaign: false },
    immediateEffects: [],
    defaultOptionId: 'env-green-none',
    expiresInMonths: 4,
    options: [
      {
        id: 'env-green-program',
        label: 'Entsiegeln und pflanzen',
        rationale: 'Vier Quartiersparks und 2.400 Straßenbäume über acht Jahre.',
        oneOffCost: 13, monthlyCost: 0.58,
        axes: { climateAmbition: 0.8, growthVsPreservation: 0.3, marketVsPublic: -0.4, fiscalRestraint: -0.4 },
        salience: { climateAmbition: 1, fiscalRestraint: 0.6, growthVsPreservation: 0.4 },
        effects: [effect({ target: 'greenSpaceHectares', expected: 46, delayMonths: 6, rampMonths: 36, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'env-green-none',
        label: 'Flächen für Wohnungsbau reservieren',
        rationale: 'Die Flächen bleiben für Bauland verfügbar.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { climateAmbition: -0.6, growthVsPreservation: -0.7, marketVsPublic: 0.5 },
        salience: { climateAmbition: 1, growthVsPreservation: 0.8 },
        effects: [effect({ target: 'unitsUnderConstruction', mode: 'rate', expected: 18, delayMonths: 6, rampMonths: 12, confidence: 'low' })],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },

  // --- Economy and finance -------------------------------------------------
  {
    schemaVersion: 1,
    id: 'eco-plant-closure',
    kind: 'external',
    category: 'economy',
    title: 'Werkschließung im Hafen: 500 Stellen',
    briefing:
      'Der größte industrielle Arbeitgeber der Stadt verlagert die Produktion. Fünfhundert Stellen und ein erheblicher Teil der Gewerbesteuer entfallen.',
    urgency: 'breaking',
    trigger: { earliestMonth: 20, latestMonth: 104, conditions: [], baseWeight: 4, cooldownMonths: 80, oncePerCampaign: true },
    immediateEffects: [effect({ target: 'businessStock', expected: -340, delayMonths: 0, rampMonths: 4, confidence: 'high' })],
    defaultOptionId: 'eco-closure-none',
    expiresInMonths: 3,
    options: [
      {
        id: 'eco-closure-transfer',
        label: 'Transfergesellschaft und Qualifizierung',
        rationale: 'Hält Beschäftigte in der Stadt und dämpft die Jugendarbeitslosigkeit.',
        oneOffCost: 7.5, monthlyCost: 0.55,
        axes: { redistribution: 0.7, marketVsPublic: -0.5, fiscalRestraint: -0.4 },
        salience: { redistribution: 1, marketVsPublic: 0.6, fiscalRestraint: 0.6 },
        effects: [effect({ target: 'integrationPlaces', expected: 180, delayMonths: 2, rampMonths: 10 })],
        sourceIds: MODEL,
      },
      {
        id: 'eco-closure-site',
        label: 'Fläche ankaufen und neu vermarkten',
        rationale: 'Hohe Anfangsinvestition, aber die Stadt steuert die Nachnutzung selbst.',
        oneOffCost: 22, monthlyCost: 0.3,
        axes: { marketVsPublic: -0.6, fiscalRestraint: -0.6, growthVsPreservation: -0.4 },
        salience: { marketVsPublic: 0.9, fiscalRestraint: 0.9 },
        effects: [effect({ target: 'businessStock', expected: 300, delayMonths: 14, rampMonths: 22, confidence: 'low' })],
        sourceIds: MODEL,
      },
      {
        id: 'eco-closure-none',
        label: 'Marktbereinigung hinnehmen',
        rationale: 'Keine kommunalen Mittel, keine Steuerung der Nachnutzung.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { marketVsPublic: 0.9, fiscalRestraint: 0.9, redistribution: -0.4 },
        salience: { marketVsPublic: 1, fiscalRestraint: 0.8, redistribution: 0.5 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'eco-datacenter',
    kind: 'decision',
    category: 'economy',
    title: 'Rechenzentrum will sich ansiedeln',
    briefing:
      'Ein Betreiber sucht 14 Hektar in Gewerbe Ost. Gewerbesteuer und wenige Arbeitsplätze stehen gegen Stromverbrauch, Flächenfraß und Abwärme.',
    urgency: 'normal',
    trigger: { earliestMonth: 24, latestMonth: 96, conditions: [], baseWeight: 5, cooldownMonths: 60, oncePerCampaign: true },
    immediateEffects: [],
    defaultOptionId: 'eco-datacenter-reject',
    expiresInMonths: 3,
    options: [
      {
        id: 'eco-datacenter-accept',
        label: 'Ansiedlung zusagen',
        rationale: 'Deutlich mehr Gewerbesteuer, spürbar mehr Emissionen und weniger Freifläche.',
        oneOffCost: 4.2, monthlyCost: -0.85,
        axes: { marketVsPublic: 0.8, climateAmbition: -0.7, growthVsPreservation: -0.6, fiscalRestraint: 0.5 },
        salience: { marketVsPublic: 0.8, climateAmbition: 1, growthVsPreservation: 0.7 },
        effects: [
          effect({ target: 'businessStock', expected: 260, delayMonths: 10, rampMonths: 14, confidence: 'high' }),
          effect({ target: 'greenSpaceHectares', expected: -14, delayMonths: 8, rampMonths: 6, confidence: 'high' }),
        ],
        sourceIds: MODEL,
      },
      {
        id: 'eco-datacenter-conditions',
        label: 'Mit Auflagen zusagen',
        rationale: 'Abwärmenutzung und Ausgleichsflächen als Bedingung. Der Betreiber verkleinert das Vorhaben.',
        oneOffCost: 5.8, monthlyCost: -0.42,
        axes: { marketVsPublic: 0.3, climateAmbition: 0.2, growthVsPreservation: -0.2 },
        salience: { marketVsPublic: 0.6, climateAmbition: 0.9, growthVsPreservation: 0.6 },
        effects: [
          effect({ target: 'businessStock', expected: 150, delayMonths: 12, rampMonths: 14 }),
          effect({ target: 'greenSpaceHectares', expected: -5, delayMonths: 8, rampMonths: 6 }),
        ],
        sourceIds: MODEL,
      },
      {
        id: 'eco-datacenter-reject',
        label: 'Ablehnen',
        rationale: 'Fläche und Klimaziele bleiben unberührt, die Einnahmen entfallen.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { climateAmbition: 0.6, growthVsPreservation: 0.6, marketVsPublic: -0.4 },
        salience: { climateAmbition: 1, growthVsPreservation: 0.7, marketVsPublic: 0.5 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'fin-maintenance-program',
    kind: 'decision',
    category: 'finance',
    title: 'Sanierungsstau wird zum Risiko',
    briefing:
      'Das Bauamt meldet Brücken, Schulen und Kanäle mit überschrittener Nutzungsdauer. Ohne dauerhaft höheren Unterhalt wächst der Stau weiter.',
    urgency: 'important',
    trigger: { earliestMonth: 9, latestMonth: 120, conditions: [{ metric: 'investmentBacklog', operator: '>', value: 112 }], baseWeight: 10, cooldownMonths: 24, oncePerCampaign: false },
    immediateEffects: [],
    defaultOptionId: 'fin-maintenance-none',
    expiresInMonths: 4,
    options: [
      {
        id: 'fin-maintenance-program',
        label: 'Unterhalt dauerhaft anheben',
        rationale: 'Der Bauunterhalt steigt über den Bedarf, der Stau schrumpft langsam und dauerhaft.',
        oneOffCost: 2.5, monthlyCost: 0,
        axes: { fiscalRestraint: -0.5, marketVsPublic: -0.3, growthVsPreservation: 0.4 },
        salience: { fiscalRestraint: 1, growthVsPreservation: 0.4 },
        effects: [effect({ target: 'maintenanceSpend', expected: 1.5, delayMonths: 1, rampMonths: 8, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'fin-maintenance-priority',
        label: 'Prioritätenliste abarbeiten',
        rationale: 'Nur die kritischsten Objekte. Billiger, hält den Stau ungefähr konstant.',
        oneOffCost: 1.2, monthlyCost: 0,
        axes: { fiscalRestraint: 0.3, growthVsPreservation: 0.2 },
        salience: { fiscalRestraint: 1 },
        effects: [effect({ target: 'maintenanceSpend', expected: 0.85, delayMonths: 1, rampMonths: 6, confidence: 'high' })],
        sourceIds: MODEL,
      },
      {
        id: 'fin-maintenance-none',
        label: 'Verschieben',
        rationale: 'Spart heute. Die Rechnung kommt als Sperrung.',
        oneOffCost: 0, monthlyCost: 0,
        axes: { fiscalRestraint: 0.9 },
        salience: { fiscalRestraint: 1 },
        effects: [],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'fin-budget-supervision',
    kind: 'chain',
    category: 'finance',
    title: 'Kommunalaufsicht fordert Haushaltssicherung',
    briefing:
      'Die Aufsichtsbehörde beanstandet die Kassenkredite. Ohne genehmigtes Sicherungskonzept werden freiwillige Leistungen gesperrt.',
    urgency: 'breaking',
    trigger: { earliestMonth: 14, latestMonth: 126, conditions: [{ metric: 'debt', operator: '>', value: 185, sustainedMonths: 4 }], baseWeight: 40, cooldownMonths: 48, oncePerCampaign: false },
    immediateEffects: [],
    defaultOptionId: 'fin-supervision-consolidate',
    expiresInMonths: 2,
    options: [
      {
        id: 'fin-supervision-consolidate',
        label: 'Konsolidierungspaket',
        rationale: 'Ausgabenschnitt quer durch alle freiwilligen Leistungen. Wirkt sofort und schmerzt überall.',
        oneOffCost: 0, monthlyCost: -2.6,
        axes: { fiscalRestraint: 0.9, redistribution: -0.6, marketVsPublic: 0.4 },
        salience: { fiscalRestraint: 1, redistribution: 0.9 },
        effects: [
          effect({ target: 'integrationPlaces', expected: -140, delayMonths: 1, rampMonths: 6, confidence: 'high' }),
          effect({ target: 'maintenanceSpend', expected: -0.4, delayMonths: 1, rampMonths: 4, confidence: 'high' }),
        ],
        sourceIds: MODEL,
      },
      {
        id: 'fin-supervision-fees',
        label: 'Gebühren und Hebesätze anheben',
        rationale: 'Mehr Einnahmen ohne Leistungsabbau, dafür höhere Belastung für Haushalte und Betriebe.',
        oneOffCost: 0.6, monthlyCost: -2.1,
        axes: { fiscalRestraint: 0.5, redistribution: -0.2, marketVsPublic: -0.2 },
        salience: { fiscalRestraint: 0.9, redistribution: 0.7, marketVsPublic: 0.5 },
        effects: [effect({ target: 'businessStock', expected: -180, delayMonths: 4, rampMonths: 12, confidence: 'medium' })],
        sourceIds: MODEL,
      },
    ],
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'gov-procurement-scandal',
    kind: 'incident',
    category: 'governance',
    title: 'Vergabeaffäre im Rathaus',
    briefing: 'Ein Bericht des Rechnungsprüfungsamts legt Verstöße bei mehreren Auftragsvergaben offen. Das Vertrauen in die Verwaltung bricht messbar ein.',
    urgency: 'breaking',
    trigger: { earliestMonth: 15, latestMonth: 120, conditions: [], baseWeight: 3, cooldownMonths: 70, oncePerCampaign: true },
    immediateEffects: [],
    options: [],
    expiresInMonths: 0,
    sourceIds: MODEL,
  },
  {
    schemaVersion: 1,
    id: 'saf-state-police',
    kind: 'external',
    category: 'safety',
    title: 'Land zieht Polizeistellen ab',
    briefing: 'Die Landespolizei verlagert 24 Stellen in den Ballungsraum. Die Stadt kann das nicht ersetzen, nur ausgleichen.',
    urgency: 'important',
    trigger: { earliestMonth: 26, latestMonth: 110, conditions: [], baseWeight: 4, cooldownMonths: 80, oncePerCampaign: true },
    immediateEffects: [effect({ target: 'orderServiceFte', expected: -18, delayMonths: 1, rampMonths: 5, confidence: 'high' })],
    options: [],
    expiresInMonths: 0,
    sourceIds: MODEL,
  },
]

export function getEvent(eventId: string): EventDefinition | undefined {
  return EVENTS.find((event) => event.id === eventId)
}

export function getEventOption(eventId: string, optionId: string) {
  return getEvent(eventId)?.options.find((option) => option.id === optionId)
}
